[metadata]
creation_date = "2024/01/03"
maturity = "development"
updated_date = "2024/01/03"

[rule]
author = ["dwb"]
description = "dwb_description"
enabled = true
from = "now-9m"
index = ["logs-*"]
interval = "5m"
language = "kuery"
name = "query_template"
risk_score = 1
rule_id = "e39dc4eb-934f-4a74-905d-041a6288012b"
severity = "low"
tags = ["dwb"]
type = "query"

query = '''
@timestamp:*
'''

